# Load libraries
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(grid)

# Download Natural Earth data
world <- ne_countries(scale = "medium", returnclass = "sf")
lakes <- ne_download(scale = 10, type = "lakes", category = "physical", returnclass = "sf")
rivers <- ne_download(scale = 10, type = "rivers_lake_centerlines", category = "physical", returnclass = "sf")

# Create the map with an "AI-Generated" watermark
ggplot(data = world) +
  geom_sf(fill = "#f4f4f2", color = "#d9d9d9", size = 0.3) +
  geom_sf(data = lakes, fill = "#a6cee3", color = NA) +
  geom_sf(data = rivers, color = "#1f78b4", size = 0.4) +
  annotation_scale(location = "bl", width_hint = 0.5, pad_x = unit(0.3, "cm"), pad_y = unit(0.3, "cm")) +
  annotation_north_arrow(location = "bl", which_north = "true", pad_x = unit(0.7, "cm"), pad_y = unit(0.7, "cm"), style = north_arrow_fancy_orienteering) +
  labs(
    title = "Epic Geographic Map",
    subtitle = "A map showcasing natural Earth features for #30DayMapChallenge",
    caption = "AI-Generated by ChatGPT"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20, hjust = 0.5, color = "#444444"),
    plot.subtitle = element_text(size = 12, hjust = 0.5, color = "#666666"),
    plot.caption = element_text(size = 10, hjust = 0.5, color = "gray"),
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "#e0f3f8", color = NA),
    plot.background = element_rect(fill = "#f7fbfc", color = NA)
  ) +
  # Add an "AI-Generated" watermark in the bottom right
  annotation_custom(
    grob = textGrob("AI-Generated by ChatGPT", gp = gpar(fontsize = 15, col = "gray", alpha = 0.6)),
    xmin = Inf, xmax = Inf, ymin = -Inf, ymax = -Inf
  )
